include:

# Reset

  - board: xiao_ble
    shield: settings_reset

  - board: nice_nano
    shield: settings_reset

# dongle

  - board: nice_nano
    shield: corne_lp_dongle dongle_display


# Keyboard

  - board: xiao_ble
    shield: corne_lp_left

  - board: xiao_ble
    shield: corne_lp_right
    
  - board: nice_nano
    shield: charybdis_left

  - board: nice_nano
    shield: charybdis_right