include:

# Reset

  # - board: xiao_ble//zmk
    # shield: settings_reset

  # - board: nice_nano//zmk
    # shield: settings_reset

# dongle

  # - board: nice_nano//zmk
    # shield: corne_lp_dongle dongle_display


# Keyboard

  # - board: xiao_ble//zmk
    # shield: corne_lp_left

  # - board: xiao_ble//zmk
    # shield: corne_lp_right
    
  - board: nice_nano//zmk
    shield: charybdis_left

  - board: nice_nano//zmk
    shield: charybdis_right
